### ISSUE TITLE
PHP 8.2: Using ${var} in strings is deprecated, use {$var} instead

### ISSUE THREAD

**Issue by calebgrove** [youngcut/kirby-form-block-suite#11]
When trying to use this plugin with PHP 8.2.0 with MAMP, the entire website will throw an error:

`Using ${var} in strings is deprecated, use {$var} instead`

The Whoops error handlers identifies this line as throwing the error: https://github.com/youngcut/kirby-form-block-suite/blob/main/classes/FormBlueprint.php#L121

Switching back to PHP 8.1.x is a functional workaround for now.

**Comment by youngcut** [comment]
Hi. Thanks for the hint. It's fixed in Version v3.4.4
