### ISSUE TITLE
Frontend not showing

### ISSUE THREAD

**Issue by chris74er** [youngcut/kirby-form-block-suite#12]
Hi, just tried the plugin in the kirby starterkit theme. Blueprint and panel workin fine but how do i get it to front?

**Comment by youngcut** [comment]
Hi Christoph
Just output the block field (that contains the form block) like this:

```
<?= $page->your_block_field()->toBlocks() ?>
```

For more information about outputing a block field, read the [manual](https://getkirby.com/docs/reference/panel/fields/blocks)

**Comment by chris74er** [comment]
Many thanks

**Comment by youngcut** [comment]
Did it work? Can i close this issue?

**Comment by chris74er** [comment]
yes, everythings fine.
