### ISSUE TITLE
Error while trying to render the form

### ISSUE THREAD

**Issue by nerdcel** [youngcut/kirby-form-block-suite#13]
Hi,

I receive the error 'Block error: "Call to a member function isFilled() on null" in block type: "form"' when I'm trying to render the form.
Any Ideas what I am missing here?

My template looks like this:
`<?= $page->contentblocks()->toBlocks() ?>`

Thanks

**Comment by youngcut** [comment]
`isFilled()` is one of the most called methods. Can you see on which file and line this is happens? (Sometimes it is written in the devtool...)

**Comment by youngcut** [comment]
But i have a litte hunch. Have you setup some blockfields? ![Bildschirmfoto 2023-03-07 um 22 44 14](https://user-images.githubusercontent.com/4754476/223571093-ebcc7f7d-a726-44ad-9bda-6a2bbfd927ca.png)

**Comment by nerdcel** [comment]
Hi,

I use the default formfields, but I just added a textfield with lastname.
The error gets thrown at the beginning of the form.php snippet. $form->showForm().
I wonder how $this can be null at this time. Just like the Class is not properly loaded/instantiated.

Maybe good to know. I am using Blade as template engine, maybe it has something to do with it.

**Comment by nerdcel** [comment]
I got it.
There is a regex expression in the Form constructor, to check if the request_uri ist from an api/panel subroute.
The regex is a bit to "loose".

For example. In my Case, I was trying to access a route named "/papier/...". So the regex matched at "/p**api**er/.."
I'll try to make a pull request to change the regex.

**Comment by youngcut** [comment]
🤦‍♂️😂 Software Development holds as such surprises day by day. Sorry man for wasting your time.
Thanks for care of it.

**Comment by nerdcel** [comment]
No worries, you're welcome
