### ISSUE TITLE
default_language in config breaks site

### ISSUE THREAD

**Issue by manuelvonrotz** [youngcut/kirby-form-block-suite#17]
Kirby 3.9.2
If I set the default_language in the config, the site breaks
```
'microman.formblock' => [
  'default_language' = 'de'
]
```

<img width="557" alt="Screenshot 2023-03-16 at 09 02 03" src="https://user-images.githubusercontent.com/6112475/225658783-576700bf-1744-45d2-be0c-b115cc57058c.png">

**Comment by youngcut** [comment]
Thanks for your your report. Could you [enable the debug-mode](https://getkirby.com/docs/reference/system/options/debug) and send me the screenshot of the error message?

**Comment by youngcut** [comment]
🤦🏻‍♂️ Thanks you guys for your feedback. I just fixed the manual.
