### ISSUE TITLE
add hook after success

### ISSUE THREAD

**Issue by bnomei** [youngcut/kirby-form-block-suite#19]
so custom events can be triggered

https://github.com/youngcut/kirby-form-block-suite/blob/766ce1ba8a6efae98f9f93402853793d158eda6f/classes/Form.php#L648

```php
kirby()->trigger('formblock.success:after', [
   'request' => $this->request,
]);
```

**Comment by bnomei** [comment]
```php
'hooks' => [
        'formblock.success:after' => function (?\microman\FormRequest $request = null) {
            
        },
    ],
```

**Comment by bnomei** [comment]
@youngcut poke :D

**Comment by youngcut** [comment]
Okay okay. It's implemented. 😜
Send me a [pm](https://microman.ch/en/microman) for your free license as thanks for your improvement.
