### ISSUE TITLE
Turn off inbox

### ISSUE THREAD

**Issue by garethworld** [youngcut/kirby-form-block-suite#20]
Is it possible to turn off the inbox? I don't want to store the messages

**Comment by youngcut** [comment]
Since the coming up of the attachment field, i needed to save the files in the project, therefore i removed the inbox-disable option.
But you can delete the request on successfully send with [this example](https://github.com/youngcut/kirby-form-block-suite#hooks).

**Comment by garethworld** [comment]
Thanks for the quick reply,  it's good I can delete the stored responses, but is there a way to remove the inbox interface? I can't store messages on the server due to GDPR, so I think this is quite an important feature.

**Comment by youngcut** [comment]
There is a way. Quick and Dirty:

Just comment the line 34 of the index.php
`//'inbox' => FormBlueprint::getInbox(),`

I'il think of it, to implement this feature.

**Comment by youngcut** [comment]
There is a way. Quick and Dirty. Just comment the line 34 of the index.php:

//'inbox' => FormBlueprint::getInbox(),

I'il think of it, to implement this feature.

Best regard.

 <https://www.microman.ch/>	
Microman | Roman Gsponer
a: Centralstrasse 16a | 6210 Sursee 
w: microman.ch <http://microman.ch/> 
p: +41 79 750 65 61
