### ISSUE TITLE
Different “Send” submit values.

### ISSUE THREAD

**Issue by smongey** [youngcut/kirby-form-block-suite#21]
Not strictly an issue but definitely a potential feature. I’d like to be able to update the submit button value “Send” and for it to be form specific rather than global.

I’m exploring using this on a site but there are multiple different form types and while I can configured the label in the config file that wont allow me to tailor this to each individual form and page.  Would be nice if this possible on the Options tab in the panel potentially. 

Is there a way to do this that I’ve perhaps missed?

**Comment by youngcut** [comment]
Is the problem solved? Can i close this issue?

**Comment by smongey** [comment]
Yep, this worked a treat.
