### ISSUE TITLE
All names showing as Formular in mailview field

### ISSUE THREAD

**Issue by smongey** [youngcut/kirby-form-block-suite#22]
I have 4/5 different form blocks across a range of pages and when I make a mailview on site.yml in a new tab it shows the page name but the form labels are all Formular despite having given them distinctive names.

**Comment by youngcut** [comment]
I do not understand your question. Can you describe the problem in more detail with screenshots?

**Comment by smongey** [comment]
My site.yml file has a tab like so…
![Screenshot 2023-05-05 at 17 42 13](https://user-images.githubusercontent.com/1285493/236517230-e5b6ee19-7bd8-4982-a159-a1b78bb8d17e.png)

The form on my customers page has the following label…
![image](https://user-images.githubusercontent.com/1285493/236517379-81877254-4ac8-417f-9c1c-705a95cc17ef.png)

The preview on the mailview tab in the site.yml still shows “Formular” despite the form having its own distinct name…
![Screenshot 2023-05-05 at 17 40 56](https://user-images.githubusercontent.com/1285493/236517066-518da83f-94de-46ac-b1db-b0f8742d04e3.png)

I would expect the label here to be Customers – Customers rather than Customers - Formular. Not a huge detail but a some pages I have the form differs in names and it would be nice for them to read accurately. 

Does that help?

**Comment by youngcut** [comment]
I see the problem. The label in the MailView shows `page name` - `form name`. But once the page is saved with a new form block, the form cannot be renamed anymore.
You can rename the form manualy: You'il find the formcontainers  under `/content/_drafts/{{form_id}}/formcontainer.txt` Change the name here and voila.

Sorry for the circumstances
