### ISSUE TITLE
[K4] Page redirect not working

### ISSUE THREAD

**Issue by whitmoa** [youngcut/kirby-form-block-suite#28]
I've installed the latest version of Form Block Suite (3.5.7) in a K4 test site and the 'on success' page redirect does not appear to be working.

I've installed from scratch and recreated my form from scratch. In the Options, I've turned on 'Redirect visitor' and selected the relevant page as the destination...

![image](https://github.com/youngcut/kirby-form-block-suite/assets/153773853/faf3508a-8287-479c-ab12-9d4ef0ec24bc)

However, when I submit through the form, which is successful and appears in the Panel, the front-end page simply refreshes with the form now gone. I assume it's behaving as if the redirect is not switched on and the page is trying to show a confirmation message, which I haven't entered.

![image](https://github.com/youngcut/kirby-form-block-suite/assets/153773853/f8609e57-048e-43d9-86d4-2b5f067f2c34)

**Comment by whitmoa** [comment]
I've just turned the redirect off and added some confirmation text but that made no difference. The form page refreshes, as before, but message does not appear.

**Comment by youngcut** [comment]
Please open the dev console and see if there's an error message.

**Comment by whitmoa** [comment]
Hi, Roman. All I'm getting in the console is this...

```
Uncaught TypeError: Cannot set properties of null (setting 'outerHTML')
    at FormBlock.onfieldvalidate (formblock.js:72:80)
    at FormBlock.onvalidate (formblock.js:59:15)
```

I hope that helps.

**Comment by youngcut** [comment]
Interesting, i had the same issue recently with an another customer. I turns out, that the templates /site/snippets/blocks/form.php comes from a older plugin version version. Please verify this file with the [one from the plugin](https://github.com/youngcut/kirby-form-block-suite/blob/main/snippets/blocks/form.php)

**Comment by whitmoa** [comment]
I do not have a form.php file in the folder /site/snippets/blocks. And the form.php file in the folder /site/plugins/form-block-suite/snippets/ is identical to the one you linked to.

**Comment by youngcut** [comment]
Can you upgrade to version 4.0.0 and check it?
To make sure that all old files are gone, please delete the folder of the form block plugin and reinstall it.

**Comment by whitmoa** [comment]
Hi, Roman. I've installed v4.0.0. All old files are gone and I had/have no overriding files in the main blueprints or snippets folders. However, I am getting the same result with both the success message and redirect options – the contact form page refreshes with an empty space where the form was.

![image](https://github.com/youngcut/kirby-form-block-suite/assets/153773853/50cc58aa-8d6c-4592-a272-de851ba909b3)

![image](https://github.com/youngcut/kirby-form-block-suite/assets/153773853/d5610c8c-5e8a-4c52-9abf-04a7af1e565b)

**Comment by youngcut** [comment]
Is this page reachable over the internet? Do you have me a link?

**Comment by whitmoa** [comment]
Happy New Year, Roman! The page is currently in a locahost dev environment. I'll promote it to my test environment, which is public-facing, and share a link soon.

**Comment by cselex** [comment]
Hi!

I have almost the same problem.
When I wanted to send a form, I got this:
![image](https://github.com/youngcut/kirby-form-block-suite/assets/1884099/aab9c4b9-3a76-4d1f-8ba2-29b00d67ac14)

Kirby 4.0.0 and your plugin is up to date.
So now it is not working, please help.

You can check on here:
http://patakimartina.iavel.hu/kapcsolat

**Comment by youngcut** [comment]
@whitmoa: Take your time. I'il close this thread too keep it clean.
You can open a new issue, if the issue still persist and you still need assistance.
Thanks for your understanding.

**Comment by whitmoa** [comment]
Hi, Roman. Thanks for your patience. I'm just pushing the site to my internet-facing UAT environment. Once done, I'll retest and, if the problem persists, I'll raise a new issue ticket.

**Comment by whitmoa** [comment]
Roman, I'm pleased to say that **the page redirect works on an internet-facing site**. Not sure why it's not working in my localhost environment, which is on XAMPP, but at least it means I can push forward with updating my client's site to Kirby 4.

No new issue ticket required. 🙂

**Comment by MickMaster** [comment]
Sorry to pick around in old stuff ... but i have the same issue here:
https://www.phaenomind.eu/de/contact
Thanks for any help ...
