### ISSUE TITLE
[K4] Submitter details not displaying in Panel

### ISSUE THREAD

**Issue by whitmoa** [youngcut/kirby-form-block-suite#29]
**[v3.5.7]**

I have the default `{{ name }} ({{ email }})` field identifiers set...

![image](https://github.com/youngcut/kirby-form-block-suite/assets/153773853/5309c03f-ab40-4954-ace7-94792f2ef1f4)

...but they are not displaying in the submission list...

![image](https://github.com/youngcut/kirby-form-block-suite/assets/153773853/1d0efbb5-6f2f-427b-b5b0-d0eb2dfd70bb)

...even though those fields have been populated (they are mandatory).

**Comment by youngcut** [comment]
This should be the id of the field. Can you post an printscreen of a single field. (e.g. name)

**Comment by whitmoa** [comment]
My form has a total of six fields, of which two have the IDs "name" and "email"...

![image](https://github.com/youngcut/kirby-form-block-suite/assets/153773853/10db9a7d-7cdc-4aa9-985b-f0f69e76ba5d)

![image](https://github.com/youngcut/kirby-form-block-suite/assets/153773853/6707f49e-6621-4d88-ab00-10f5a5de6ceb)

Those two fields are used as the Display title – `{{name}} ({{email}})` – but they are not displaying.

One point to note is that I have always had issues with being able to control/edit the default name and email fields that are present after installation, so I usually delete and recreate them but still with the same IDs. That's never been an issue previously but I thought I would mention it if that might be part of the issue this time.

**Comment by youngcut** [comment]
Thanks for your precise description. Can you try it with commented '_' customized template.
You wrote "[v3.5.7]" at the beginning of this thread. Is this your Kirby version? In this case i recomment you use the [previous valid version for Kirby3](https://github.com/youngcut/kirby-form-block-suite/tree/v3.5.2).

**Comment by whitmoa** [comment]
Sorry, Roman, but I'm not sure what you mean by "commented '_' template".

v3.5.7 is the Form Block Suite version, i.e. the latest one. My Kirby version is 4.0.1.

**Comment by youngcut** [comment]
I could reproduce your problem. Please stay tuned. I'il fix it asap...

**Comment by youngcut** [comment]
It's fixed in Version 4.0.0.
