### ISSUE TITLE
Validation / messages not sending on Child pages

### ISSUE THREAD

**Issue by mactedder80** [youngcut/kirby-form-block-suite#3]
My forms are all working on root-level pages. However, when I put a new form on a child page, the form doesn't validate. I get the 'contact the administrator' message.

**Comment by youngcut** [comment]
This message comes out, if the debug mode of your kirby is disable. Could you turn on `debug => true` in your config and see what the plugin complains?
If the debug mode is on and/or you get the same message, check the return of the validation request with your devtool. Tell me, if you need help to do this.

**Comment by mactedder80** [comment]
I have turned on `debug => true` - I looked in the web-inspector and it says:

`[Error] Failed to load resource: the server responded with a status of 400 (Bad Request) (validator, line 0).      https://www.mywebsite.com/form/validator`

**Comment by mactedder80** [comment]
Any luck with resolving this issue? The site I am using this on is live, so a fix would be great.

**Comment by youngcut** [comment]
To reproduce your issue. I need a copy of your form blocks on both pages. Could you post/mail me?

**Comment by mactedder80** [comment]
Sure, what email address?

**Comment by youngcut** [comment]
You can send it to mail@microman.ch

**Comment by mactedder80** [comment]
Thanks - I have sent this over.
