### ISSUE TITLE
[K4] Form 'summary' not highlighting new submissions

### ISSUE THREAD

**Issue by whitmoa** [youngcut/kirby-form-block-suite#30]
**[v3.5.7]**

Even when there are new form submissions, the summary highlight built into the form block is grey, rather than green, and shows no numbers in the brackets. In this screenshot, I have two new submissions, but you'd only know that by opening the side drawer. There is no in-page indication.

![image](https://github.com/youngcut/kirby-form-block-suite/assets/153773853/1977a856-692f-4149-8c06-e8f464e47c6b)

![image|653x217, 50%](https://github.com/youngcut/kirby-form-block-suite/assets/153773853/7edd3938-de3d-4b47-9f08-c742a749001f)

**Comment by youngcut** [comment]
Copy of #29
