### ISSUE TITLE
Not working with Hungarian language settings

### ISSUE THREAD

**Issue by cselex** [youngcut/kirby-form-block-suite#31]
Hi Youngcut!

I started a new website in the Hungarian language.
I set in the config this:
`'microman.formblock' => [
        'default_language' => 'hu'
 ],`
and my user language is Hungarian too.

This is what I saw:
![image](https://github.com/youngcut/kirby-form-block-suite/assets/1884099/cec35763-147e-47a9-ae4d-db111410b1b5)

I tried with de and en languages and it worked.

**Comment by youngcut** [comment]
Hi. Thanks for reporting. it's fixed in [v4.0.1](https://github.com/youngcut/kirby-form-block-suite/releases/tag/v4.0.1)
