### ISSUE TITLE
Unexpected token <!DOCTYPE

### ISSUE THREAD

**Issue by youngcut** [youngcut/kirby-form-block-suite#32]
Hi!

When I wanted to send a form, I got this:
![image](https://github.com/youngcut/kirby-form-block-suite/assets/1884099/aab9c4b9-3a76-4d1f-8ba2-29b00d67ac14)

Kirby 4.0.0 and your plugin is up to date.
So now it is not working, please help.

You can check on here:
http://patakimartina.iavel.hu/kapcsolat

_Originally posted by @cselex in https://github.com/youngcut/kirby-form-block-suite/issues/28#issuecomment-1880155461_

**Comment by youngcut** [comment]
Hi Cselex

Your problem is, that your endpoint item is missing:

<img width="385" alt="Bildschirmfoto 2024-01-07 um 21 45 44" src="https://github.com/youngcut/kirby-form-block-suite/assets/4754476/7a7a8487-ea99-408d-b2be-b7aa75154fe3">

Usealy it's given from the script.php in the formcore folder:

https://github.com/youngcut/kirby-form-block-suite/blob/81f9b8af8a1161822d6727f16eef7251e8d076f2/snippets/blocks/formcore/script.php#L11

Can you check this file in your environment, to check whats wrong..?

**Comment by cselex** [comment]
I checked and got it the first problem.
I had 3. x.x version files in the site/snippets folder, for example, the core folder, and form.php.
So I removed these but I got another error on the console:
![image](https://github.com/youngcut/kirby-form-block-suite/assets/1884099/0f199fae-e0a1-4ac2-b063-20bc41415e41)

You can check on the website.

**Comment by youngcut** [comment]
I checked it. You have still some leftovers from the old version.
e.g. Please make sure the all the input fields has a `[data-form="form_error"]` attribute.
For testing you can (temporarly) remove the folder/files `site/snipptes/blocks/form*`

**Comment by cselex** [comment]
Yes, I find that too.
I removed almost all files from the form templates folder and it works again!!!
So I'm sorry for this, in the future I try to check twice my changes and the new version.

Oh and thanks the Hun fix :)

**Comment by youngcut** [comment]
I'm glad I could help. 🤗
