### ISSUE TITLE
Strange class in error => &quot;formblock__message__list&quot;

### ISSUE THREAD

**Issue by cselex** [youngcut/kirby-form-block-suite#33]
Hi!
I find this after I get an error message on the form.

![image](https://github.com/youngcut/kirby-form-block-suite/assets/1884099/c6bd9e11-fd40-4704-a9fc-a0c4900e2fe6)

I checked the code but I don't see anything.
You can check here:
http://patakimartina.iavel.hu/kapcsolat

**Comment by youngcut** [comment]
I verified your network traffic with one of my test environment. And there is a different:

Test environment:
```
{"state":"invalid","error_message":"
<div class=\"formblock__message--error\" data-form=\"form_error\">
```

Your environment:
```
{"state":"invalid","error_message":"
<div class='\"formblock__message--error\"' data-form='\"form_error\"'>
```

Please check, if there is no custom template in your installation.
Especally: `site/snippets/blocks/formtemplate/form_error.php`

**Comment by cselex** [comment]
I don't have modified form_error.php. Removed all modified files from snippets.

**Comment by cselex** [comment]
Ok maybe I got it!
I got off the kirby-minify-html plugin and the form started to work well.
