### ISSUE TITLE
Send confirmation email field cannot handle variables

### ISSUE THREAD

**Issue by cselex** [youngcut/kirby-form-block-suite#36]
Welcome!

Could you fix the email field to be able to handle email or variables?
In the case of a confirmation email, I receive the email from a variable.
I know it can be solved in code, but please fix it, it would be useful in the long run if you don't have to pay attention to this when updating.
Thank you so much for your attention and participation.

**Comment by youngcut** [comment]
Thank you for your request.
Unfortunately, I do not fully understand your request.
Can you perhaps add an example to the problem?

**Comment by cselex** [comment]
Hi!
Yes I show you.
When activate the "Visszaigazolás küldése" options I can add emails for the E-mail field (active field) but I need a variable here.
![image](https://github.com/youngcut/kirby-form-block-suite/assets/1884099/c4246af7-67cb-4b0e-914b-f6a62d1969b4)

**Comment by youngcut** [comment]
What kind of variable..? Have you tried {{your-variable}}?

**Comment by cselex** [comment]
Yes I tried:
![image](https://github.com/youngcut/kirby-form-block-suite/assets/1884099/54e23aeb-fed1-461d-b06d-2bbb0f604f9c)

**Comment by youngcut** [comment]
I see. For security reason, this feature is not allowed.
But you can use the [success hook](https://github.com/youngcut/kirby-form-block-suite?tab=readme-ov-file#hook-success).
The `$request` object contains also the fields data, where you can take the `email` variable and [sending an email](https://getkirby.com/docs/guide/emails)
