### ISSUE TITLE
Mailview single entry preview.

### ISSUE THREAD

**Issue by smongey** [youngcut/kirby-form-block-suite#37]
![image](https://github.com/youngcut/kirby-form-block-suite/assets/1285493/42f5e6e5-2860-4923-96aa-69f29258b7ae)

When I have a series of fields and try to view the responses in a mailview and click the i icon the dialog popup default presentation is a little rough as you can see and I cant actually see the data that’s users have submit.

Any ideas on how best to address this?

**Comment by youngcut** [comment]
Thanks for your input. It's fixed in Version 4.0.2.
