### ISSUE TITLE
Always get filesize Error.

### ISSUE THREAD

**Issue by manuel-fleig** [youngcut/kirby-form-block-suite#38]
No matter if I enter a random number or leave the field empty, I always get a filesize error: "should not be bigger than -9.5367431640625E-7MB"

**Comment by youngcut** [comment]
Here is a excerpt from the **readme.md**

*Note for attachment field type: To increase the maximum file size set the upload_max_filesize, post_max_size and memory_limit to desiered values in your php.ini.*

Have you checked this..?

**Comment by manuel-fleig** [comment]
ah thanks, sorry, didn’t see that section. but can i still use the field in the panel then?

**Comment by youngcut** [comment]
Of corse. Why you shouldn't use the attachment field in the panel..?
