### ISSUE TITLE
Send confirmation email field cannot handle variables - Vol2

### ISSUE THREAD

**Issue by cselex** [youngcut/kirby-form-block-suite#39]
Prev issue: https://github.com/youngcut/kirby-form-block-suite/issues/36

You are welcome,
Has there been an incident in the past that this is the answer to?
Look, I use the plugin so that if the customer wants to set up an automatic reply message, he can do so with a few clicks without any extra coding. In this form, the response block in the plugin makes no sense. 
Please remove the block or have a solution so that a variable can also be used.
I opened a new ticket because my problem was not solved.

**Comment by cselex** [comment]
Hello Youngcut,
No problem :)
Maybe I didn't express myself well. 
So I still need to be able to enter a variable into the field according to the attached figure.
Because I need the setting so that the sender can send a reply letter. And no extra coding is required.
Thanks in advance for your help

![image](https://github.com/youngcut/kirby-form-block-suite/assets/1884099/f2802f4e-b61e-4d80-9e89-e7c32e5f8c31)

**Comment by youngcut** [comment]
This may sound funny, but I would like to thank you for being so persistent. 😜
While looking through the code, I actually found the bug you mentioned and fixed it right away.
Check [Version 4.1.0](https://github.com/youngcut/kirby-form-block-suite/releases/tag/v4.1.0) and let me know, if everything works as aspected...

**Comment by cselex** [comment]
Hello

I thank you for dealing with my problem :D
I checked your modification.
Question: Do I have to define in the yaml file which field the response messages should be sent based on?

**Comment by youngcut** [comment]
I don't know if i understand your question right.
I'm adding a `form_field` setting in v4.1.1 right now. ([See the manual](https://github.com/youngcut/kirby-form-block-suite?tab=readme-ov-file#email-field))
Do this the answer your question..?

**Comment by cselex** [comment]
Yes, great, thanks!
