### ISSUE TITLE
From email address includes www.

### ISSUE THREAD

**Issue by mactedder80** [youngcut/kirby-form-block-suite#5]
How do I change the default 'from email address?

Currently, emails sent from the forms come from 'noreply@www.mywebsite.com'  - the www. part needs to be removed.

Also can the 'reply to address' and 'sent from address' be changed per form?

**Comment by youngcut** [comment]
This can be set in you config file. [Check this out!](https://github.com/youngcut/kirby-form-block-suite#email-adress-for-outgoing-emails)
You can set it per form adding a [custom message](https://github.com/youngcut/kirby-form-block-suite#messages) named `from_email`.

**Comment by mactedder80** [comment]
Do I just put it in the 'site>config>config.php' file? ie:

`return [
     'debug' => false,
     'smartypants' => true,
     'panel' =>[
       'install' => false
     ],
     
     'microman.formblock' => [
        'from_email' => 'info@example.com'
      ]
 ];`

**Comment by mactedder80** [comment]
Yes that works - Thanks.
