### ISSUE TITLE
Question: is it possible to configure the sort order of submissions in the Panel?

### ISSUE THREAD

**Issue by brandsis** [youngcut/kirby-form-block-suite#50]
I've only just noticed that the form submissions displayed in the Panel slide-out tray are not sorted chronologically. Read submissions always appear at the bottom but unread ones seem to be in a random order.

**Is it possible to set the sort order to newest first?** Is there a config setting I've missed in the docs?

![image](https://github.com/youngcut/kirby-form-block-suite/assets/153773853/0871fd7e-d727-4268-9451-8533aceb2406)

**Comment by youngcut** [comment]
That's true. That's a bug. It will be fixed in 4.2.1.
