### ISSUE TITLE
Help integrating Cloudflare Turnstile?

### ISSUE THREAD

**Issue by brandsis** [youngcut/kirby-form-block-suite#54]
Hi, Roman.

On my own website, I have your spam protection field added and I'm happy with it. But I have a couple of charity clients that I am migrating to Kirby and one of those is a dementia-related charity. They're not keen on the maths problem CAPTCHA because asking someone to complete a maths problem, however simple, is not the right thing for a dementia-focussed website. As a result, I've been looking at implementing Cloudflare Turnstile.

I can get the [client-side rendering](https://developers.cloudflare.com/turnstile/get-started/client-side-rendering/) working by using JavaScript to insert the Turnstile script, the form widget and an `action` attribute to the `form` element on [my TEST site](https://brandsistency.dev/brandsistency/contact).

It's the [server-side validation](https://developers.cloudflare.com/turnstile/get-started/server-side-validation/) that's the challenge. I found a [relevant tutorial](https://clifford.io/blog/implement-cloudflare-turnstile-with-php/) and even reached out to the author. Of course, the form processing doesn't use the `action` instruction and so the call to the Cloudflare servers to get the validation response doesn't happen.

The tutorial author's advice was to... _"hook into the form plugin's validation code, so that it can run the CF validation code first (and trigger error/redirect upon failure), followed by its own validation/email tasks upon success. This way, you won't need your JS hacks and can ensure the validation flow is correct."_ But that's beyond my level of expertise.

Is this something you'd be able to help with? I'm keen to have Turnstile as an option. And I think it would be a useful addition to the plugin.

Many thanks.

**Comment by youngcut** [comment]
Dear Brandsis

Your request goes far beyond the support of this plugin. Unfortunately, I cannot offer you any support here.

Thank you for your understanding.

**Comment by brandsis** [comment]
Thanks, Roman. Understood. I'll try to figure it out.
