### ISSUE TITLE
Getting 3 mails instead of one

### ISSUE THREAD

**Issue by romanustin** [youngcut/kirby-form-block-suite#8]
I am getting 3 mails both for owner and the one who filled the form. Thought maybe it's because of number of translations for plugin, as I had 3, but then checked with 4 translations, still the same - getting 3 mails on every submit.

**Comment by romanustin** [comment]
First I was using 2 version, created this form, then deleted old plugin completele, and uploaded 3 beta version, everything seems to work, only started to get 3 mails. I did some changes in 2 version, but only in style of template. Can check to create new form.

**Comment by romanustin** [comment]
No, same thing, created new form, also getting 3 mails.

**Comment by youngcut** [comment]
Do you have files in `site/snippets/blocks/formfields` or is there a file called `site/snippets/blocks/form.php`?

**Comment by romanustin** [comment]
Ok, tried to remove templates with similar names, not the case.

**Comment by romanustin** [comment]
Removing controller didn't help.

**Comment by youngcut** [comment]
Hi. It's fixed in Version [v3.3.6-BETA](https://github.com/youngcut/kirby-form-block-suite/releases/tag/v3.3.6-BETA)
